<?php $initial_options = array(
'administrator_tracked' => 'no',
'analytics_tracking_id' => '',
'author_tracked' => 'yes',
'back_office_tracked' => 'no',
'contributor_tracked' => 'yes',
'editor_tracked' => 'yes',
'front_office_tracked' => 'yes',
'javascript_enabled' => 'yes',
'optimizer_tracking_id' => '',
'subscriber_tracked' => 'yes',
'version' => CONTENT_SWITCHER_VERSION,
'visitor_tracked' => 'yes');