<?php add_option('content_switcher', array(
'analytics_tracking_admin' => 'no',
'analytics_tracking_author' => 'yes',
'analytics_tracking_contributor' => 'yes',
'analytics_tracking_editor' => 'yes',
'analytics_tracking_id' => 'UA-XXXXXXXX-X',
'analytics_tracking_subscriber' => 'yes',
'analytics_tracking_visitor' => 'yes',
'javascript_enabled' => 'no',
'optimizer_tracking_id' => 'UA-XXXXXXXX-X'));