<?php $tables['members'] = array(
'id' => array('type' => 'int', 'name' => __('ID', 'membership-manager'), 'width' => 5),
'category_id' => array('type' => 'int', 'name' => __('Category ID', 'membership-manager'), 'width' => 12),
'login' => array('type' => 'text', 'name' => __('Login name', 'membership-manager'), 'width' => 12, 'searchby' => __('the login name', 'membership-manager')),
'password' => array('type' => 'text'),
'first_name' => array('type' => 'text', 'name' => __('First name', 'membership-manager'), 'width' => 12, 'searchby' => __('the first name', 'membership-manager')),
'last_name' => array('type' => 'text', 'name' => __('Last name', 'membership-manager'), 'width' => 12, 'searchby' => __('the last name', 'membership-manager')),
'email_address' => array('type' => 'text', 'name' => __('Email address', 'membership-manager'), 'width' => 15, 'searchby' => __('the email address', 'membership-manager')),
'website_name' => array('type' => 'text', 'name' => __('Website', 'membership-manager'), 'width' => 15, 'searchby' => __('the website name', 'membership-manager')),
'website_url' => array('type' => 'text', 'name' => __('Website URL', 'membership-manager'), 'width' => 18, 'searchby' => __('the website URL', 'membership-manager')),
'address' => array('type' => 'text', 'name' => __('Address', 'membership-manager'), 'width' => 15, 'searchby' => __('the address', 'membership-manager')),
'postcode' => array('type' => 'text', 'name' => __('Postcode', 'membership-manager'), 'width' => 9, 'searchby' => __('the postcode', 'membership-manager')),
'town' => array('type' => 'text', 'name' => __('Town', 'membership-manager'), 'width' => 12, 'searchby' => __('the town', 'membership-manager')),
'country' => array('type' => 'text', 'name' => __('Country', 'membership-manager'), 'width' => 12, 'searchby' => __('the country', 'membership-manager')),
'phone_number' => array('type' => 'text', 'name' => __('Phone number', 'membership-manager'), 'width' => 12, 'searchby' => __('the phone number', 'membership-manager')),
'ip_address' => array('type' => 'text', 'name' => __('IP address', 'membership-manager'), 'width' => 12, 'searchby' => __('the IP address', 'membership-manager')),
'user_agent' => array('type' => 'text', 'name' => __('User agent', 'membership-manager'), 'width' => 24, 'searchby' => __('the user agent', 'membership-manager')),
'referring_url' => array('type' => 'text', 'name' => __('Referring URL', 'membership-manager'), 'width' => 18, 'searchby' => __('the referring URL', 'membership-manager')),
'status' => array('type' => 'text', 'default' => 'active', 'name' => __('Status', 'membership-manager'), 'width' => 12),
'members_areas' => array('type' => 'text', 'name' => __('Members areas', 'membership-manager'), 'width' => 12),
'date' => array('type' => 'datetime', 'name' => __('Registration date', 'membership-manager'), 'width' => 18, 'searchby' => __('the registration date', 'membership-manager')),
'date_utc' => array('type' => 'datetime', 'name' => __('Registration date (UTC)', 'membership-manager'), 'width' => 18, 'searchby' => __('the registration date (UTC)', 'membership-manager')));

$tables['members_areas'] = array(
'id' => array('type' => 'int', 'name' => __('ID', 'membership-manager'), 'width' => 5),
'category_id' => array('type' => 'int', 'name' => (strstr($_GET['page'], 'categories') ? __('Parent category ID', 'membership-manager') : __('Category ID', 'membership-manager')), 'width' => 12),
'name' => array('type' => 'text', 'name' => __('Name', 'membership-manager'), 'width' => 18, 'searchby' => __('the name', 'membership-manager')),
'description' => array('type' => 'text', 'name' => __('Description', 'membership-manager'), 'width' => 18, 'searchby' => __('the description', 'membership-manager')),
'keywords' => array('type' => 'text', 'name' => __('Keywords', 'membership-manager'), 'width' => 18, 'searchby' => __('the keywords', 'membership-manager')),
'url' => array('type' => 'text', 'name' => __('URL', 'membership-manager'), 'width' => 18, 'searchby' => __('the URL', 'membership-manager')),
'instructions' => array('type' => 'text', 'name' => __('Instructions to the member', 'membership-manager'), 'width' => 18, 'searchby' => __('the instructions to the member', 'membership-manager')),
'members_areas' => array('type' => 'text', 'name' => __('Included members areas', 'membership-manager'), 'width' => 18),
'date' => array('type' => 'datetime', 'name' => __('Creation date', 'membership-manager'), 'width' => 18, 'searchby' => __('the creation date', 'membership-manager')),
'date_utc' => array('type' => 'datetime', 'name' => __('Creation date (UTC)', 'membership-manager'), 'width' => 18, 'searchby' => __('the creation date (UTC)', 'membership-manager')),
'registration_confirmation_url' => array('type' => 'text', 'name' => __('Registration confirmation URL', 'membership-manager'), 'width' => 18, 'searchby' => __('the registration confirmation URL', 'membership-manager')),
'members_initial_category_id' => array('type' => 'text', 'name' => __('Members initial category', 'membership-manager'), 'width' => 15),
'members_initial_status' => array('type' => 'text', 'name' => __('Members initial status', 'membership-manager'), 'width' => 15),
'registration_confirmation_email_sent' => array('type' => 'text', 'name' => __('Registration confirmation email sent', 'membership-manager'), 'width' => 15),
'registration_confirmation_email_sender' => array('type' => 'text', 'name' => __('Sender of the registration confirmation email', 'membership-manager'), 'width' => 15, 'searchby' => __('the sender of the registration confirmation email', 'membership-manager')),
'registration_confirmation_email_receiver' => array('type' => 'text', 'name' => __('Receiver of the registration confirmation email', 'membership-manager'), 'width' => 15, 'searchby' => __('the receiver of the registration confirmation email', 'membership-manager')),
'registration_confirmation_email_subject' => array('type' => 'text', 'name' => __('Subject of the registration confirmation email', 'membership-manager'), 'width' => 15, 'searchby' => __('the subject of the registration confirmation email', 'membership-manager')),
'registration_confirmation_email_body' => array('type' => 'text', 'name' => __('Body of the registration confirmation email', 'membership-manager'), 'width' => 18, 'searchby' => __('the body of the registration confirmation email', 'membership-manager')),
'registration_notification_email_sent' => array('type' => 'text', 'name' => __('Registration notification email sent', 'membership-manager'), 'width' => 15),
'registration_notification_email_sender' => array('type' => 'text', 'name' => __('Sender of the registration notification email', 'membership-manager'), 'width' => 15, 'searchby' => __('the sender of the registration notification email', 'membership-manager')),
'registration_notification_email_receiver' => array('type' => 'text', 'name' => __('Receiver of the registration notification email', 'membership-manager'), 'width' => 15, 'searchby' => __('the receiver of the registration notification email', 'membership-manager')),
'registration_notification_email_subject' => array('type' => 'text', 'name' => __('Subject of the registration notification email', 'membership-manager'), 'width' => 15, 'searchby' => __('the subject of the registration notification email', 'membership-manager')),
'registration_notification_email_body' => array('type' => 'text', 'name' => __('Body of the registration notification email', 'membership-manager'), 'width' => 18, 'searchby' => __('the body of the registration notification email', 'membership-manager')),
'member_subscribed_to_autoresponder' => array('type' => 'text', 'name' => __('Members subscribed to an autoresponder list', 'membership-manager'), 'width' => 18),
'member_autoresponder' => array('type' => 'text', 'name' => __('Members autoresponder', 'membership-manager'), 'width' => 12, 'searchby' => __('the members autoresponder', 'membership-manager')),
'member_autoresponder_list' => array('type' => 'text', 'name' => __('Members autoresponder list', 'membership-manager'), 'width' => 15, 'searchby' => __('the members autoresponder list', 'membership-manager')),
'registration_custom_instructions_executed' => array('type' => 'text', 'name' => __('Custom instructions executed', 'membership-manager'), 'width' => 15),
'registration_custom_instructions' => array('type' => 'text', 'name' => __('PHP code of the custom instructions', 'membership-manager'), 'width' => 18, 'searchby' => __('the PHP code of the custom instructions', 'membership-manager')));

$tables['members_areas_categories'] = $tables['members_areas'];

$tables['members_categories'] = array(
'id' => array('type' => 'int', 'name' => __('ID', 'membership-manager'), 'width' => 5),
'category_id' => array('type' => 'int', 'name' => __('Parent category ID', 'membership-manager'), 'width' => 12),
'name' => array('type' => 'text', 'name' => __('Name', 'membership-manager'), 'width' => 18, 'searchby' => __('the name', 'membership-manager')),
'description' => array('type' => 'text', 'name' => __('Description', 'membership-manager'), 'width' => 18, 'searchby' => __('the description', 'membership-manager')),
'keywords' => array('type' => 'text', 'name' => __('Keywords', 'membership-manager'), 'width' => 18, 'searchby' => __('the keywords', 'membership-manager')),
'members_areas' => array('type' => 'text', 'name' => __('Members areas', 'membership-manager'), 'width' => 12),
'date' => array('type' => 'datetime', 'name' => __('Creation date', 'membership-manager'), 'width' => 18, 'searchby' => __('the creation date', 'membership-manager')),
'date_utc' => array('type' => 'datetime', 'name' => __('Creation date (UTC)', 'membership-manager'), 'width' => 18, 'searchby' => __('the creation date (UTC)', 'membership-manager')));